language: node_js
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
sudo: required
dist: bionic
node_js: 9.11

addons:
apt:
  sources:
  - google-chrome
  packages:
  - google-chrome-stable
  - google-chrome-beta

before_script:
- npm install -g angular-cli
- npm install

script:
- ng test -sm=false
